platform :ios, '13.0'

use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'SwiftyRDLib_Example' do
  pod 'SwiftyRDLib', :path => '../'
  pod 'lottie-ios'
  pod 'Alamofire'
  pod 'SDWebImage', '5.18.7'
 
  target 'SwiftyRDLib_Tests' do
    inherit! :search_paths

    
  end
end
